package com.pjj.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.pjj.db.WeatherBean;

import com.pjj.db.WeatherBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig weatherBeanDaoConfig;

    private final WeatherBeanDao weatherBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        weatherBeanDaoConfig = daoConfigMap.get(WeatherBeanDao.class).clone();
        weatherBeanDaoConfig.initIdentityScope(type);

        weatherBeanDao = new WeatherBeanDao(weatherBeanDaoConfig, this);

        registerDao(WeatherBean.class, weatherBeanDao);
    }
    
    public void clear() {
        weatherBeanDaoConfig.clearIdentityScope();
    }

    public WeatherBeanDao getWeatherBeanDao() {
        return weatherBeanDao;
    }

}
