package com.pjj.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WEATHER_BEAN".
*/
public class WeatherBeanDao extends AbstractDao<WeatherBean, Long> {

    public static final String TABLENAME = "WEATHER_BEAN";

    /**
     * Properties of entity WeatherBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Hour = new Property(1, int.class, "hour", false, "HOUR");
        public final static Property Date = new Property(2, String.class, "date", false, "DATE");
        public final static Property Json = new Property(3, String.class, "json", false, "JSON");
        public final static Property Area = new Property(4, String.class, "area", false, "AREA");
    }


    public WeatherBeanDao(DaoConfig config) {
        super(config);
    }
    
    public WeatherBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WEATHER_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"HOUR\" INTEGER NOT NULL ," + // 1: hour
                "\"DATE\" TEXT NOT NULL ," + // 2: date
                "\"JSON\" TEXT NOT NULL ," + // 3: json
                "\"AREA\" TEXT NOT NULL );"); // 4: area
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WEATHER_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, WeatherBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getHour());
        stmt.bindString(3, entity.getDate());
        stmt.bindString(4, entity.getJson());
        stmt.bindString(5, entity.getArea());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, WeatherBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getHour());
        stmt.bindString(3, entity.getDate());
        stmt.bindString(4, entity.getJson());
        stmt.bindString(5, entity.getArea());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public WeatherBean readEntity(Cursor cursor, int offset) {
        WeatherBean entity = new WeatherBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // hour
            cursor.getString(offset + 2), // date
            cursor.getString(offset + 3), // json
            cursor.getString(offset + 4) // area
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, WeatherBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setHour(cursor.getInt(offset + 1));
        entity.setDate(cursor.getString(offset + 2));
        entity.setJson(cursor.getString(offset + 3));
        entity.setArea(cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(WeatherBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(WeatherBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(WeatherBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
